In [16]:
import os
import sklearn
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

from sklearn.linear_model import LinearRegression as sk_OLS
# from sklearn.compose import ColumnTransformer
# from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split

import torch
import torch.nn.functional as F
import math

# from sklearn.metrics import r2_score
# import string
# import nltk
# from nltk.corpus import stopwords
from nltk.corpus import wordnet as wn
# from nltk.stem import WordNetLemmatizer, PorterStemmer
from sklearn.metrics import accuracy_score  # Import the accuracy_score function
import re
# from collections import Counter
# from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer, TfidfTransformer
# from sklearn.linear_model import LogisticRegression

In [17]:
def scaller(edu):
    x_max = max(edu)
    x_min = min(edu)
    scaled_xs =[]
    for x in edu:
        x_scaled = 4*(x-x_min)/(x_max-x_min)+1
        scaled_xs.append(x_scaled)
    return scaled_xs

In [18]:
longitudinal = pd.read_csv("datacsv/oasis_longitudinal.csv")
cross_sectional = pd.read_csv("datacsv/oasis_cross-sectional.csv")

edu = longitudinal.EDUC
scalled_edu = scaller(edu)
longitudinal["Educ"] = scalled_edu

frames = [cross_sectional, longitudinal]


combined = pd.concat(frames)
# combined = combined.rename(columns={"Group": "CDR"})
# combined = combined.map(rename)
# combined["Group"] = combined["Group"].astype('float')
# print(combined)
combined.reset_index(inplace=True, drop=True)


print(combined)
combined.to_csv("combined.csv")

                ID M/F Hand  Age      Educ  SES  MMSE  CDR  eTIV   nWBV  \
0    OAS1_0001_MR1   F    R   74  2.000000  3.0  29.0  0.0  1344  0.743   
1    OAS1_0002_MR1   F    R   55  4.000000  1.0  29.0  0.0  1147  0.810   
2    OAS1_0003_MR1   F    R   73  4.000000  3.0  27.0  0.5  1454  0.708   
3    OAS1_0004_MR1   M    R   28       NaN  NaN   NaN  NaN  1588  0.803   
4    OAS1_0005_MR1   M    R   18       NaN  NaN   NaN  NaN  1737  0.848   
..             ...  ..  ...  ...       ...  ...   ...  ...   ...    ...   
804            NaN   M    R   82  3.352941  1.0  28.0  0.5  1693  0.694   
805            NaN   M    R   86  3.352941  1.0  26.0  0.5  1688  0.675   
806            NaN   F    R   61  2.647059  2.0  30.0  0.0  1319  0.801   
807            NaN   F    R   63  2.647059  2.0  30.0  0.0  1327  0.796   
808            NaN   F    R   65  2.647059  2.0  30.0  0.0  1333  0.801   

       ASF  Delay Subject ID         MRI ID        Group  Visit  MR Delay  \
0    1.306    NaN     

In [19]:
# combined['M/F_new'], categories = pd.factorize(combined["M/F"])
# combined['Hand_new'], categories = pd.factorize(combined["Hand"])

In [20]:
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

cdr_na = combined["CDR"].isna()
# print(combined[cdr_na])


unlabled = combined[cdr_na]
labled = combined[~cdr_na]


print(len(labled)/len(combined))

y_label = labled.CDR
X_label = labled.drop([ "M/F", "Hand", "Subject ID", "MRI ID", "ID", "Group", "Visit", "EDUC", "Delay", "ASF", "CDR", "MR Delay"], axis=1)
# X_cluster_label = X_label.drop(["MR Delay", "SES", "MMSE"], axis=1)

# , "SES", "MMSE", "ASF"
x_unlabeled = unlabled.drop([ "M/F", "Hand", "Subject ID", "MRI ID", "ID", "Group", "Visit", "EDUC", "Delay", "ASF", "CDR", "MR Delay"], axis=1)
print(X_label)


0.7515451174289246
     Age      Educ  SES  MMSE  eTIV   nWBV
0     74  2.000000  3.0  29.0  1344  0.743
1     55  4.000000  1.0  29.0  1147  0.810
2     73  4.000000  3.0  27.0  1454  0.708
8     74  5.000000  2.0  30.0  1636  0.689
9     52  3.000000  2.0  30.0  1321  0.827
..   ...       ...  ...   ...   ...    ...
804   82  3.352941  1.0  28.0  1693  0.694
805   86  3.352941  1.0  26.0  1688  0.675
806   61  2.647059  2.0  30.0  1319  0.801
807   63  2.647059  2.0  30.0  1327  0.796
808   65  2.647059  2.0  30.0  1333  0.801

[608 rows x 6 columns]


In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.fit(X_label))
print(scaler.mean_)
X_label = scaler.transform(X_label)
# np.nan_to_num(X_scaled, copy=False, nan=-1)
# X_scaled.nan_to_num(value=-1, inplace=True)
print(X_label)

def scale_non_cat(x):
    scaler = StandardScaler()
    x_s = x["eTIV",   "nWBV"]
    print(scaler.fit(x_s))

    x_s = scaler.transform(X_label)
    # np.nan_to_num(X_scaled, copy=False, nan=-1)
    # X_scaled.nan_to_num(value=-1, inplace=True)
    print(x_s)
    x["eTIV",   "nWBV"]

    


StandardScaler()
[7.52088816e+01 3.08320433e+00 2.47192982e+00 2.72343234e+01
 1.47706250e+03 7.37129934e-01]
[[-0.12264306 -1.11252064  0.46853768  0.47916067 -0.7803639   0.13768155]
 [-2.05022486  0.94160821 -1.30599042  0.47916067 -1.93569835  1.70915693]
 [-0.22409473  0.94160821  0.46853768 -0.06358955 -0.1352533  -0.68323842]
 ...
 [-1.44151482 -0.44794954 -0.41872637  0.75053578 -0.92697995  1.49806322]
 [-1.23861147 -0.44794954 -0.41872637  0.75053578 -0.88006282  1.38078894]
 [-1.03570812 -0.44794954 -0.41872637  0.75053578 -0.84487496  1.49806322]]


In [22]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
print(scaler.fit(X_label))
print(scaler.mean_)
X_label = scaler.transform(X_label)
# np.nan_to_num(X_scaled, copy=False, nan=-1)
# X_scaled.nan_to_num(value=-1, inplace=True)
print(X_label)

def scale_non_cat(x):
    scaler = StandardScaler()
    x_s = x["eTIV",   "nWBV"]
    print(scaler.fit(x_s))

    x_s = scaler.transform(X_label)
    # np.nan_to_num(X_scaled, copy=False, nan=-1)
    # X_scaled.nan_to_num(value=-1, inplace=True)
    print(x_s)
    x["eTIV",   "nWBV"]

    


# normalize values:
# explicitly require this experimental feature
from sklearn.experimental import enable_iterative_imputer
# now you can import normally from sklearn.impute
from sklearn.impute import IterativeImputer


imp_mean = IterativeImputer(random_state=42)
X_label = imp_mean.fit_transform(X_label)
X_label = pd.DataFrame(X_label, columns=["Age","Educ",  "SES",  "MMSE",  "eTIV", "nWBV"])

X = x_unlabeled
x_infered_labels = imp_mean.transform(X)
x_infered_labels = pd.DataFrame(x_infered_labels, columns=["Age", "Educ", "SES", "MMSE", "eTIV", "nWBV"])
frames = [X_label, x_infered_labels]


combined = pd.concat(frames)
# y_label = combined.CDR
# combined = combined.drop(["CDR"], axis=1)


StandardScaler()
[-1.63611814e-16  1.11022302e-16  7.47939722e-17 -1.39235891e-16
  5.84327908e-18  1.28552140e-16]
[[-0.12264306 -1.11252064  0.46853768  0.47916067 -0.7803639   0.13768155]
 [-2.05022486  0.94160821 -1.30599042  0.47916067 -1.93569835  1.70915693]
 [-0.22409473  0.94160821  0.46853768 -0.06358955 -0.1352533  -0.68323842]
 ...
 [-1.44151482 -0.44794954 -0.41872637  0.75053578 -0.92697995  1.49806322]
 [-1.23861147 -0.44794954 -0.41872637  0.75053578 -0.88006282  1.38078894]
 [-1.03570812 -0.44794954 -0.41872637  0.75053578 -0.84487496  1.49806322]]


/Users/msturman00/Library/Python/3.9/lib/python/site-packages/sklearn/base.py:458: UserWarning: X has feature names, but IterativeImputer was fitted without feature names
  warnings.warn(


In [23]:
import numpy as np
from sklearn.decomposition import PCA

pca = PCA(n_components=5)
x_components = pca.fit_transform(X_label)
# print(pca.explained_variance_ratio_)
# print(pca.singular_values_)

In [24]:
X_train, X_test, y_train, y_test = train_test_split(x_components, y_label)
print(len(X_train))
# print(y_train)
print(len(X_test))
print(y_label)
# print(X_test)
y_train = y_train.astype('int')
y_test = y_test.astype('int')

456
152
0      0.0
1      0.0
2      0.5
8      0.0
9      0.0
      ... 
804    0.5
805    0.5
806    0.0
807    0.0
808    0.0
Name: CDR, Length: 608, dtype: float64


In [25]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

clf_svm = make_pipeline(StandardScaler(), SVC(gamma='auto'))
clf_svm.fit(X_train, y_train)
y_pred = clf_svm.predict(X_test)
print('Accuracy: ', accuracy_score(y_test, y_pred))




# y_unlabeled = clf_svm.predict(x_unlabeled)
# print(y_unlabeled)

Accuracy:  0.9210526315789473


In [26]:
x_un_components = pca.fit_transform(x_infered_labels)

y_unlabeled = clf_svm.predict(x_un_components)
print(y_unlabeled)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [38]:
from xgboost import XGBClassifier

# create model instance
# print(y_label)
# X_train, X_test, y_train, y_test = train_test_split(combined, y_label)
bst = XGBClassifier(n_estimators=112, max_depth=7, learning_rate=.5, objective='reg:quantileerror')
# fit model
bst.fit(X_train, y_train)
y_pred = bst.predict(X_test)
print('Accuracy: ', accuracy_score(y_test, y_pred))

y_unlabeled = bst.predict(x_un_components)
print(y_unlabeled)
print()

/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):


Accuracy:  0.9473684210526315
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]



In [39]:
from xgboost import XGBClassifier

# create model instance
# print(y_label)
# X_train, X_test, y_train, y_test = train_test_split(combined, y_label)
bst = XGBClassifier(n_estimators=100, max_depth=5, learning_rate=.1, objective='reg:quantileerror')
# fit model
bst.fit(X_train, y_train)
y_pred = bst.predict(X_test)
print('Accuracy: ', accuracy_score(y_test, y_pred))

y_unlabeled = bst.predict(x_un_components)
print(y_unlabeled)
print()

/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):


Accuracy:  0.9473684210526315
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]



In [42]:
from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

bst = XGBClassifier(n_estimators=112, max_depth=7, learning_rate=.5, objective='reg:quantileerror')

# Define the parameter grid to search
param_grid = {
    'n_estimators': [100,112, 117, 122, 133, 156, 164, 150, 170, 200, 234, 254, 267, 284, 300],
    'learning_rate': [0.01, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8],
    'max_depth': [3, 4, 5, 6, 7, 8],
    'min_child_weight': [1, 2, 3, 4, 5, 6, 7, 8],
}

# Initialize the XGBoost classifier
xgb_model = XGBClassifier(random_state=42)

# Initialize GridSearchCV with the XGBoost model and parameter grid
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, cv=3, scoring='accuracy')

# Fit the grid search to your training data
grid_search.fit(X_train, y_train)

# Get the best hyperparameters from the grid search
best_params = grid_search.best_params_

# Train a new XGBoost model with the best hyperparameters
best_xgb_model = XGBClassifier(random_state=42, **best_params)
best_xgb_model.fit(X_train, y_train)

# Make predictions and evaluate the best model
y_pred_xgb = best_xgb_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_xgb)

# Print the best hyperparameters and accuracy
print('Best Hyperparameters:', best_params)
print('Best XGB Model Accuracy:', accuracy)


/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
/Users/msturman00/Library/Python/3.9/lib/python/site-pac

In [34]:
from xgboost import XGBClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.metrics import accuracy_score
import numpy as np

# Define the parameter distributions to sample from
param_dist = {
    'n_estimators': np.arange(100, 501, 100),
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 4, 5],
    'min_child_weight': np.arange(1, 9),
}

# Initialize the XGBoost classifier
xgb_model = XGBClassifier(random_state=42)

# Initialize RandomizedSearchCV with the XGBoost model and parameter distributions
random_search = RandomizedSearchCV(estimator=xgb_model, param_distributions=param_dist, n_iter=10, cv=3, scoring='accuracy', random_state=42)

# Fit the randomized search to your training data
random_search.fit(X_train, y_train)

# Get the best hyperparameters from the randomized search
best_params = random_search.best_params_

# Train a new XGBoost model with the best hyperparameters
best_xgb_model = XGBClassifier(random_state=42, **best_params)
best_xgb_model.fit(X_train, y_train)

# Make predictions and evaluate the best model
y_pred_xgb = best_xgb_model.predict(X_test)
accuracy = accuracy_score(y_test, y_pred_xgb)

# Print the best hyperparameters and accuracy
print('Best Hyperparameters:', best_params)
print('Best XGB Model Accuracy:', accuracy)


/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
/Users/msturman00/Library/Python/3.9/lib/python/site-pac

Best Hyperparameters: {'n_estimators': 100, 'min_child_weight': 2, 'max_depth': 4, 'learning_rate': 0.2}
Best XGB Model Accuracy: 0.9407894736842105


/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):


In [36]:
from xgboost import XGBClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.model_selection import RandomizedSearchCV
from sklearn.model_selection import train_test_split
import numpy as np

# Define the parameter distributions for XGBoost
param_dist_xgb = {
    'n_estimators': np.arange(100, 501, 100),
    'learning_rate': [0.01, 0.1, 0.2],
    'max_depth': [3, 4, 5],
    'min_child_weight': np.arange(1, 9),
}

# Initialize the XGBoost classifier
xgb_model = XGBClassifier(random_state=42)

# Initialize RandomizedSearchCV with the XGBoost model and parameter distributions
random_search_xgb = RandomizedSearchCV(estimator=xgb_model, param_distributions=param_dist_xgb, n_iter=10, cv=3, scoring='accuracy', random_state=42)

# Fit the randomized search to your training data
random_search_xgb.fit(X_train, y_train)

# Get the best hyperparameters from the randomized search for XGBoost
best_params_xgb = random_search_xgb.best_params_

# Train a new XGBoost model with the best hyperparameters
best_xgb_model = XGBClassifier(random_state=42, **best_params_xgb)
best_xgb_model.fit(X_train, y_train)

# Make predictions using the best XGBoost model
y_pred_xgb = best_xgb_model.predict(X_test)

# Updated parameter grid for Random Forest with valid 'max_features' options
param_grid_rf_xgb = {
    'n_estimators': [best_params_xgb['n_estimators']],
    'max_depth': [best_params_xgb['max_depth']],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2']  # Use valid options for 'max_features'
}

# Initialize the Random Forest classifier
rf_model = RandomForestClassifier(random_state=42)

# Initialize GridSearchCV with the Random Forest model and parameter grid using the best XGBoost hyperparameters
grid_search_rf_xgb = GridSearchCV(estimator=rf_model, param_grid=param_grid_rf_xgb, cv=3, scoring='accuracy')

# Fit the grid search to your training data
grid_search_rf_xgb.fit(X_train, y_train)

# Get the best hyperparameters from the grid search for Random Forest with XGBoost hyperparameters
best_params_rf_xgb = grid_search_rf_xgb.best_params_

# Train a new Random Forest model with the best hyperparameters
best_rf_model_xgb = RandomForestClassifier(random_state=42, **best_params_rf_xgb)
best_rf_model_xgb.fit(X_train, y_train)

# Make predictions using the best Random Forest model with XGBoost hyperparameters
y_pred_rf_xgb = best_rf_model_xgb.predict(X_test)

# Calculate accuracy for both models and compare
accuracy_xgb = accuracy_score(y_test, y_pred_xgb)
accuracy_rf_xgb = accuracy_score(y_test, y_pred_rf_xgb)

# Print the best XGBoost hyperparameters and accuracy, and the best Random Forest hyperparameters and accuracy
print('Best XGBoost Hyperparameters:', best_params_xgb)
print('XGBoost Model Accuracy:', accuracy_xgb)
print('\nBest Random Forest Hyperparameters with XGBoost Hyperparameters:', best_params_rf_xgb)
print('Random Forest Model Accuracy with XGBoost Hyperparameters:', accuracy_rf_xgb)

/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
/Users/msturman00/Library/Python/3.9/lib/python/site-packages/xgboost/data.py:520: FutureWarning: is_sparse is deprecated and will be removed in a future version. Check `isinstance(dtype, pd.SparseDtype)` instead.
  if is_sparse(data):
/Users/msturman00/Library/Python/3.9/lib/python/site-pac

Best XGBoost Hyperparameters: {'n_estimators': 100, 'min_child_weight': 2, 'max_depth': 4, 'learning_rate': 0.2}
XGBoost Model Accuracy: 0.9407894736842105

Best Random Forest Hyperparameters with XGBoost Hyperparameters: {'max_depth': 4, 'max_features': 'sqrt', 'min_samples_leaf': 1, 'min_samples_split': 10, 'n_estimators': 100}
Random Forest Model Accuracy with XGBoost Hyperparameters: 0.9210526315789473
